version: '3.8'

services:
  mkdocs:
    image: squidfunk/mkdocs-material:9.5.17
    command: ${AF_MKDOCS_COMMAND} # For normal development this variable can simply be empty, but during deployment this gets set to "build"
    volumes:
      - ./:/docs
    working_dir: /docs
    ports:
      - 8000:8000