site_name: AssetFetch
markdown_extensions:
  - def_list
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 0
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/AssetFetch/web
repo_name: AssetFetch/web
theme:
  name: material
  palette:
    scheme: assetfetch
  logo: media/icon_cube.svg
  favicon: media/icon_cube.svg
  features:
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
nav:
  - "Start": index.md
  - "How It Works": "how-it-works.md"
  - "For Artists": for-artists.md
  - "For Providers": for-providers.md
  #- "For Client Developers": for-client-devs.md
  - "Specification":
      - "Latest Draft": spec/latest-draft.md
      - v0.3: spec/0.3.md
      - v0.2: spec/0.2.md
      - v0.1: spec/0.1.md

extra_css:
  - stylesheets/theme.css
