name: AssetFetch.org Website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
env:
  AF_MKDOCS_COMMAND: build
jobs:
  assetfetch-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: Build using Docker
          run: mkdir ${PWD}/site/ && docker compose up

        # Runs a single command using the runners shell
        - name: FTP Deploy
          # You may pin to the exact commit or the version.
          # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
              # ftp server
              server: ${{vars.WEBSITE_FTP_SERVER}}
              # ftp username
              username: ${{vars.WEBSITE_FTP_LOGIN}}
              # ftp password
              password: ${{secrets.WEBSITE_FTP_PASSWORD}}
              # Path to upload to on the server. Must end with trailing slash /
              server-dir: /public/
              local-dir: ./site/